/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Beans.City;
import Beans.CityDirectory;
import Beans.Community;
import Beans.Doctor;
import Beans.DoctorDirectory;
import Beans.Hospital;
import Beans.HospitalDirectory;
import Beans.House;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author preks
 */
public class DoctorManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorManagementPanel
     */
    CityDirectory cityDirectory;
    public DoctorManagementPanel() {
        initComponents();
    }

    DoctorManagementPanel(CityDirectory cityDirectory) {
        this.cityDirectory = cityDirectory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_create = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bt_update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bt_delete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        bt_view = new javax.swing.JButton();
        txt_city = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txt_phonoNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_hospital = new javax.swing.JTextField();
        txt_license = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_special = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_experience = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        bt_view1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bt_create.setBackground(new java.awt.Color(196, 225, 255));
        bt_create.setText("Create");
        bt_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_createActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        bt_update.setBackground(new java.awt.Color(196, 225, 255));
        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });

        jLabel3.setText("City");

        bt_delete.setBackground(new java.awt.Color(196, 225, 255));
        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Community");

        jLabel5.setText("Phono");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        bt_view.setBackground(new java.awt.Color(196, 225, 255));
        bt_view.setText("View");
        bt_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_viewActionPerformed(evt);
            }
        });

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Docter Management");

        jTable1.setBackground(new java.awt.Color(217, 231, 244));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sr.No", "Name", "City", "Community", "Phone No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        jLabel8.setText("Hospital");

        txt_hospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hospitalActionPerformed(evt);
            }
        });

        txt_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_licenseActionPerformed(evt);
            }
        });

        jLabel13.setText("Specialization");

        txt_special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_specialActionPerformed(evt);
            }
        });

        jLabel14.setText("Experience");

        txt_experience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_experienceActionPerformed(evt);
            }
        });

        jLabel16.setText("License");

        bt_view1.setBackground(new java.awt.Color(196, 225, 255));
        bt_view1.setText("Reload");
        bt_view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_view1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_phonoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_special, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txt_experience, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_license, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bt_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_create, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_update, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_view, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_delete)
                    .addComponent(bt_update)
                    .addComponent(bt_create)
                    .addComponent(bt_view)
                    .addComponent(bt_view1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_phonoNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_special, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_experience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        // TODO add your handling code here:
        
        String name = txt_name.getText();
            if ((name.equals(""))
            || (!name.matches("^[a-zA-Z]*$"))
            || (name == null))
            {
            name = JOptionPane.showInputDialog(this, "Name invalid");  
            }
        
        
        Long contact_no = Long.parseLong(txt_phonoNo.getText());
        Pattern p = Pattern.compile("^\\d{10}$");
        Matcher m = p.matcher(txt_phonoNo.getText());
        
        if(!m.matches())
        {
            contact_no = Long.parseLong(JOptionPane.showInputDialog(this, "Contact number invalid "));

        }
        
        
        String regex2 =  "[0-9]+";
            int experiense= 0;
            if(!txt_experience.getText().matches(regex2))
            {
                experiense = Integer.parseInt(JOptionPane.showInputDialog(this, "Invalid zip"));
            }
            else{
            experiense = Integer.parseInt(txt_experience.getText());
            }       
        String city = txt_city.getText(); 
        String commTxt = jTextField3.getText();    
        String hosp_txt = txt_hospital.getText();
        System.out.println("##############1");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selected_row = jTable1.getSelectedRow();
        Doctor doctor = (Doctor)model.getValueAt(selected_row, 0);
        City citySelected = (City)model.getValueAt(selected_row, 2);
        Community communitySelected = (Community)model.getValueAt(selected_row, 3);
        System.out.println("##############2");

        if(jTable1.getSelectedRowCount() == 1) {

                    System.out.println("##############3");

            int indexCity = cityDirectory.getCityDirectory().indexOf(citySelected);
            
            ArrayList<Community> comDir = cityDirectory.getCityDirectory().get(indexCity).getCommunityDir();
                    System.out.println("##############4");
                    
            for(Community community: comDir)
            {
                if(community.getName().equals(communitySelected.getName()))
                {
                    ArrayList<Hospital> hopitalDir = community.getHospitalDirectory().getHospitalDirectory();
                   
                    for(Hospital hospital: hopitalDir)
                    {
                         System.out.println("##############5");
                        if(hospital.getName().equals(hosp_txt))
                            {
                                for(Doctor doctorInfo:hospital.getDocterDirector().getDocterDirectory())
                                {
                                    if(doctorInfo.getId() == doctor.getId())
                                    {
                                        doctorInfo.setName(txt_name.getText());
                                        doctorInfo.setSpecialization(txt_special.getText());
                                        doctorInfo.setExperience(experiense);
                                        doctorInfo.setLicense(txt_license.getText());
                                        doctorInfo.setContactNo(contact_no);
                                        doctorInfo.setUsername(txt_username.getText());
                                        doctorInfo.setPassword(txt_password.getText());
        
                                    }
                                }
                                //house.setName(name);
                            }
                        
                    }
               
                JOptionPane.showMessageDialog( this, "Hospital updated .");
                }  
            }        
        }
        else
        {
            JOptionPane.showMessageDialog( this, "Please select a row");
        }
        System.out.println("##############6");
        populate();     
    }//GEN-LAST:event_bt_updateActionPerformed

    
    public void populate()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for(City c: cityDirectory.getCityDirectory())
        {
            ArrayList<Community> commDirectory = c.getCommunityDir();
            for(Community comm:commDirectory)
            {
                HospitalDirectory hospitalDirectory = comm.getHospitalDirectory();
                 for(Hospital hsp:hospitalDirectory.getHospitalDirectory()){
                     DoctorDirectory doctorDirectory = hsp.getDocterDirector();
                     for(Doctor doc:doctorDirectory.getDocterDirectory()){
                Object[] row = new Object[7];
                row[0] = doc;
                row[1] = doc.getName();
                row[2] = c;
                row[3] = comm;
                row[4] = doc.getContactNo();
                 
                  ArrayList<House> houseDirectory = comm.getHouseDir();
                 for(House house: houseDirectory){
                    row[5] = house.getId();
                    row[6] = house.getName();
                 }
                model.addRow(row);

                     }
                
            }
                
                 
                 
        }
    }
    }

    
    
    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_hospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hospitalActionPerformed

    private void bt_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_createActionPerformed
        // TODO add your handling code here:
        CreateDoctorFrame docterFrame = new CreateDoctorFrame(cityDirectory);
        docterFrame.show();
    }//GEN-LAST:event_bt_createActionPerformed

    private void bt_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_viewActionPerformed
        // TODO add your handling code here:
        
       int selectedRowIndex = jTable1.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to View");
            return;   
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Doctor doctorInfo = (Doctor) model.getValueAt(selectedRowIndex, 0);
        txt_name.setText(doctorInfo.getName());
        txt_city.setText(doctorInfo.getCity());
        jTextField3.setText(doctorInfo.getCommunity());
        txt_phonoNo.setText(String.valueOf(doctorInfo.getContactNo()));
        txt_hospital.setText(doctorInfo.getHospital());
        txt_username.setText(doctorInfo.getUsername());
        txt_password.setText(doctorInfo.getPassword());
        txt_special.setText(doctorInfo.getSpecialization());
        txt_experience.setText(String.valueOf(doctorInfo.getExperience()));
        txt_license.setText(doctorInfo.getLicense());
         
        
        
    }//GEN-LAST:event_bt_viewActionPerformed

    private void txt_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_licenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_licenseActionPerformed

    private void txt_specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_specialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_specialActionPerformed

    private void txt_experienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_experienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_experienceActionPerformed

    private void bt_view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_view1ActionPerformed
        // TODO add your handling code here:
        populate();
    }//GEN-LAST:event_bt_view1ActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
       
        int selectedRowIndex = jTable1.getSelectedRow();
        
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
           
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selected_row = jTable1.getSelectedRow();
        Doctor doctorInfo = (Doctor)model.getValueAt(selected_row, 0);
        //Hospital hospitalInfo = (Hospital)model.getValueAt(selected_row, 0);
        City cityInfo = (City)model.getValueAt(selected_row, 2);
        Community communitySelected = (Community)model.getValueAt(selected_row, 3);
         if(jTable1.getSelectedRowCount() == 1) {
             int indexCity = cityDirectory.getCityDirectory().indexOf(cityInfo);
            
            ArrayList<Community> comDir = cityDirectory.getCityDirectory().get(indexCity).getCommunityDir();
//             Hospital hsp1 = new Hospital();       
            for(Community community: comDir)
            {
                if(community.getName().equals(communitySelected.getName()))
                {
                    HospitalDirectory hospitalDir = community.getHospitalDirectory();
                    for(Hospital hospital:hospitalDir.getHospitalDirectory())
                    {
                        if(hospital.getName().equals(doctorInfo.getHospital()))
                        {
                            DoctorDirectory docDir = hospital.getDocterDirector();
                            docDir.deleteDoctor(doctorInfo);
                        }
                    }
                }  
            }
            
         }
        JOptionPane.showMessageDialog(this, "Doctor deleted.");
//        System.out.println("")
//        hospitalDirectory.deleteHospital(selectedinfo);
        populate();
              
    }//GEN-LAST:event_bt_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_create;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_update;
    private javax.swing.JButton bt_view;
    private javax.swing.JButton bt_view1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_experience;
    private javax.swing.JTextField txt_hospital;
    private javax.swing.JTextField txt_license;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phonoNo;
    private javax.swing.JTextField txt_special;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
